#!/usr/bin/env bash

#### wiringOP - A webcam Service for multiple Cams and Stream Services.
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021
#### https://github.com/mainsail-crew/wiringOP
####
#### This File is distributed under GPLv3
####

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

# Module only Variables
CN_BUILD_PACKAGE_FILE="/tmp/cn_packages.lst"

# Helper Func
is_raspbian() {
    if [[ -f /boot/config.txt ]] && [[ -f /etc/rpi-issue ]]; then
        echo "1"
    else
        echo "0"
    fi
}

get_pkglist() {
    if [[ "$(is_raspbian)" = "1" ]]; then
        CN_BUILD_INSTALL_SH="/home/${BASE_USER}/wiringOP/tools/libs/pkglist-rpi.sh"
    fi
    if [[ "$(is_raspbian)" = "0" ]]; then
        CN_BUILD_INSTALL_SH="/home/${BASE_USER}/wiringOP/tools/libs/pkglist-generic.sh"
    fi
}

echo_green "Installing wiringOP ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone wiringOP repo
echo_green "Clone wiringOP repository ..."
gitclone WIRINGOP_REPO wiringOP

## Step 3: Move to wiringOP as working directory
pushd "/home/${BASE_USER}/wiringOP" &> /dev/null || exit 1

## Step 4: Run wiringOP install routine
echo_green "Compile wiringOP ..."
./build

## Step 5: Leave wiringOP
popd &> /dev/null || exit 1

## Step 6: leave home dir
popd &> /dev/null || exit 1

## Finish
echo_green "Installing wiringOP ... DONE!"
