#!/usr/bin/env bash

#### wiringOP - This is a GPIO access library for OrangePi.
####
#### https://github.com/orangepi-xunlong/wiringOP
####
####

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Installing wiringOP ..."

## Force apt update
apt-get update
## Make sure 'git' is installed!
check_install_pkgs git

## Step 1: Move to Home Dir as WorkingDirectoy
pushd "/home/${BASE_USER}" &> /dev/null || exit 1

## Step 2: clone wiringOP repo
echo_green "Clone wiringOP repository ..."
gitclone WIRINGOP_REPO wiringOP

## Step 3: Move to wiringOP as working directory
pushd "/home/${BASE_USER}/wiringOP" &> /dev/null || exit 1

## Step 4: Run wiringOP install routine
echo_green "Compile wiringOP ..."
./build

## Step 5: Leave wiringOP
popd &> /dev/null || exit 1

## Step 6: leave home dir
popd &> /dev/null || exit 1

## Finish
echo_green "Installing wiringOP ... DONE!"
