#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"

DOWNLOAD_BASE_URL="https://github.com/kabroxiko/armbian-builds/releases/latest/download"

# Image source
# DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}.xz.sha"
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/armbian-orangepi_zeroplus2_h5_bookworm.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/armbian-orangepi_zeroplus2_h5_bookworm.img.xz"

BASE_IMAGE_ENLARGEROOT=3000
MODULES="base(pkgupgrade,udev_fix,armbian(armbian_net,mainsailos,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar,wiringOP,klipper-serial-btt,artillery))"

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
export BASE_IMAGE_ENLARGEROOT
export MODULES

### JSON sniplet Setup
### NOTE: Please see all config files for setup variables!!!
# shellcheck disable=SC2034
JSON_PRETTY_SBC_NAME="Orange Pi Zero Plus 2 H5"
# shellcheck disable=SC2034
JSON_SUPPORTED_SBC="orangepizeroplus2-h5-64bit"
